// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wx_cos_auth.proto

package wx_cos_auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAuthDataRequest struct {
	Method               string   `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Pathname             string   `protobuf:"bytes,2,opt,name=pathname" json:"pathname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthDataRequest) Reset()         { *m = GetAuthDataRequest{} }
func (m *GetAuthDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthDataRequest) ProtoMessage()    {}
func (*GetAuthDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_wx_cos_auth_9a052e1da5f91954, []int{0}
}
func (m *GetAuthDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthDataRequest.Unmarshal(m, b)
}
func (m *GetAuthDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthDataRequest.Marshal(b, m, deterministic)
}
func (dst *GetAuthDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthDataRequest.Merge(dst, src)
}
func (m *GetAuthDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthDataRequest.Size(m)
}
func (m *GetAuthDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthDataRequest proto.InternalMessageInfo

func (m *GetAuthDataRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *GetAuthDataRequest) GetPathname() string {
	if m != nil {
		return m.Pathname
	}
	return ""
}

type GetAuthDataReply struct {
	AuthData             string   `protobuf:"bytes,1,opt,name=auth_data,json=authData" json:"auth_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthDataReply) Reset()         { *m = GetAuthDataReply{} }
func (m *GetAuthDataReply) String() string { return proto.CompactTextString(m) }
func (*GetAuthDataReply) ProtoMessage()    {}
func (*GetAuthDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_wx_cos_auth_9a052e1da5f91954, []int{1}
}
func (m *GetAuthDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthDataReply.Unmarshal(m, b)
}
func (m *GetAuthDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthDataReply.Marshal(b, m, deterministic)
}
func (dst *GetAuthDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthDataReply.Merge(dst, src)
}
func (m *GetAuthDataReply) XXX_Size() int {
	return xxx_messageInfo_GetAuthDataReply.Size(m)
}
func (m *GetAuthDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthDataReply proto.InternalMessageInfo

func (m *GetAuthDataReply) GetAuthData() string {
	if m != nil {
		return m.AuthData
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAuthDataRequest)(nil), "wx_cos_auth.GetAuthDataRequest")
	proto.RegisterType((*GetAuthDataReply)(nil), "wx_cos_auth.GetAuthDataReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WXCosAuthClient is the client API for WXCosAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WXCosAuthClient interface {
	GetAuthData(ctx context.Context, in *GetAuthDataRequest, opts ...grpc.CallOption) (*GetAuthDataReply, error)
}

type wXCosAuthClient struct {
	cc *grpc.ClientConn
}

func NewWXCosAuthClient(cc *grpc.ClientConn) WXCosAuthClient {
	return &wXCosAuthClient{cc}
}

func (c *wXCosAuthClient) GetAuthData(ctx context.Context, in *GetAuthDataRequest, opts ...grpc.CallOption) (*GetAuthDataReply, error) {
	out := new(GetAuthDataReply)
	err := c.cc.Invoke(ctx, "/wx_cos_auth.WXCosAuth/GetAuthData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WXCosAuthServer is the server API for WXCosAuth service.
type WXCosAuthServer interface {
	GetAuthData(context.Context, *GetAuthDataRequest) (*GetAuthDataReply, error)
}

func RegisterWXCosAuthServer(s *grpc.Server, srv WXCosAuthServer) {
	s.RegisterService(&_WXCosAuth_serviceDesc, srv)
}

func _WXCosAuth_GetAuthData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WXCosAuthServer).GetAuthData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wx_cos_auth.WXCosAuth/GetAuthData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WXCosAuthServer).GetAuthData(ctx, req.(*GetAuthDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WXCosAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wx_cos_auth.WXCosAuth",
	HandlerType: (*WXCosAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthData",
			Handler:    _WXCosAuth_GetAuthData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wx_cos_auth.proto",
}

func init() { proto.RegisterFile("wx_cos_auth.proto", fileDescriptor_wx_cos_auth_9a052e1da5f91954) }

var fileDescriptor_wx_cos_auth_9a052e1da5f91954 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xaf, 0x88, 0x4f,
	0xce, 0x2f, 0x8e, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0xf2, 0xe0, 0x12, 0x72, 0x4f, 0x2d, 0x71, 0x2c, 0x2d, 0xc9, 0x70, 0x49, 0x2c, 0x49,
	0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0xcb, 0x4d, 0x2d, 0xc9, 0xc8,
	0x4f, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0xa4, 0xb8, 0x38, 0x0a, 0x12,
	0x4b, 0x32, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x32, 0x70, 0xbe, 0x92, 0x3e, 0x97, 0x00,
	0x8a, 0x49, 0x05, 0x39, 0x95, 0x42, 0xd2, 0x5c, 0x9c, 0x20, 0x5b, 0xe2, 0x53, 0x12, 0x4b, 0x12,
	0xa1, 0x46, 0x71, 0x24, 0x42, 0x55, 0x18, 0xc5, 0x70, 0x71, 0x86, 0x47, 0x38, 0xe7, 0x17, 0x83,
	0xb4, 0x08, 0xf9, 0x73, 0x71, 0x23, 0xe9, 0x16, 0x92, 0xd7, 0x43, 0x76, 0x37, 0xa6, 0x0b, 0xa5,
	0x64, 0x71, 0x2b, 0x28, 0xc8, 0xa9, 0x54, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xd6, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x14, 0xf1, 0x5c, 0x0b, 0x01, 0x01, 0x00, 0x00,
}
